version: '3.8'

services:
  michael_scott_bot:
    build: .
    container_name: michael_scott_bot
    restart: always
    environment:
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_SECRET=${TWITTER_ACCESS_SECRET}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    volumes:
      - huggingface_cache:/root/.cache/huggingface/transformers  # 🔹 Evitará descargas repetidas
    command: ["python", "src/main.py"]

volumes:
  huggingface_cache:
